### PR TITLE
Add integration tests

### PR DESCRIPTION
**Pull request by hermanjunge**
Just a quick integration test to save us the trouble of loading the package locally, firing the browser and simulate the arduino calls. Just type `mocha` :-)

### CODE REVIEW

**Comment by hermanjunge** [comment]
## Why I did these tests? (i.e. motivation)

You can just run the product locally, fire a browser to see if its working, and in another tab, to pull the `GET` call to simulate the arduino's working. But, seriously, that is like 5 minutes testing. OK, 2 minutes for a skilled QA person. Just to see if it works, right?

I propose to do the same process in an automate test. In this machine, a MBP, It takes +/- 874 milliseconds. In other words, I could even hook the firing of this test for each save if I want, to see that my changes does not break everything (extreme case, of course).

Well, that's for the "selling point". Now, I wanted to do the test because the app rests on the power of the socket.io library to operate, and I never did a headless browser automate test on an socket.io powered web application. Fortunately, it worked.

## How to execute these tests

Just install [mocha](http://mochajs.org/) in your machine. Then, in the root directory of the repository, do

	mocha

## Developing notes (i.e. tools and caveats found)

* This is an integration test, in other words, we treat the app as a black box that we only call though HTTP calls, and see, via these very HTTP calls, if it is rendering what we want or not. Given these constraints, we must: a) Run the app in a child process, not loading the express app in the test and b) Use a headless browser to see what is being rendered.

* Why a headless browser? Because there is javascript running in the pages.

* Why I decided to copy the jquery and socket.io CDN files? Just to save time in the tests. Without this "mocking" (in quotes because they are the very same files, obtained via `curl`), we can take up to 5 seconds extra instead of the less-than-a-second time we currently take.

* Socket.io: Oh this one... The normal way to use zombie would just order the `browser` object to `visit` the URL `/status` and just read the result. The problem is that socket.io takes care to keep on executing code to maintain the connection _until_ you stop to wait in zombie. After you decide to "stop waiting",  You can't regist any change. OK. I spent a lot of time figuring out how to do it, and in the end, the trick is to declare the `browser.visit('/status')` and then order `browser.wait(someBooleanFunctionToCheck, callback)` function. The latter, will take care of process the loading of the javascript files and etc, until some condition given in `someBooleanFunctionToCheck` happens. Cool, so we can use the `wait` one function anytime after we fire some request emulating arduinos. Then we check the html at the moment with `browser.html()`. Bottom line here is that in every `before` function of the tests, we call this `wait` function after emulating the arduino request, so we let the processes in the webpage to receive somehow the socket.io update. And only after then, we can check the html to see if there were changes or not.

* The rest is textbook TDD. Here is a sample of the output:

screen shot 2015-02-11 at 16 19 59

**Comment by hermanjunge** [comment]
Added the above notes as requested by @flockonus in the tech interview.

**Comment by dgipps** [comment]
Looks really good Herman. When I have some time I will properly review them.

Thanks!

**Comment by flockonus** [comment]
Thanks Herman, looks great!

**Pull request merged**
